# all fields must be filled.

mysql:
  host: '127.0.0.1'
  port: 3306
  user: 'root'
  password: '1234'
  db: 'test'
  server_id: 2  # this should be unique. this may be different depending on environment.
  log_file: 'mysql-bin.000001' # this may be different depending on environment.
  log_pos: 0

es:
  host: '127.0.0.1'
  port: 9200